version: "3.9"

services:
  db:
    image: postgres
    container_name: rimun-db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - rimun
    restart: always

  db-gui:
    image: dpage/pgadmin4
    container_name: rimun-db-gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./db-gui-data:/var/lib/pgadmin
    networks:
      - rimun
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    container_name: ps-api
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/usr/src/rimun
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    depends_on:
      - db
      - db-gui
    networks:
      - rimun

networks:
  rimun:
    name: "rimun-network"

volumes:
  db-data:
    driver: local
  db-gui-data:
    driver: local
