ALTER SEQUENCE "forum_id_seq" RESTART WITH 1;
ALTER SEQUENCE "resource_id_seq" RESTART WITH 1;
ALTER SEQUENCE "group_id_seq" RESTART WITH 1;
ALTER SEQUENCE "role_id_seq" RESTART WITH 1;
ALTER SEQUENCE "country_id_seq" RESTART WITH 1;
